name: Continuous Deployment Prod

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name:  Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          tags: manojkr999/todo-next-app:${{ github.sha }}
          push: true

      - name: Clone ops repo and update image tags
        env:
          PAT: ${{ secrets.PAT }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          git clone https://x-access-token:${PAT}@github.com/Manoj-Kumar-Munda/ops.git
          cd ops
          sed -i "s|\(image: manojkr999/todo-next-app:\)[^[:space:]]*|\1${IMAGE_TAG}|" manifest.yml
          grep "manojkr999/todo-next-app:${IMAGE_TAG}" manifest.yml
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add manifest.yml
          git commit -m "Update image tag to ${IMAGE_TAG}"
          git push https://${PAT}@github.com/Manoj-Kumar-Munda/ops.git HEAD:master